# Generated by Django 5.1.1 on 2024-09-26 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_test', '0002_alter_useranswer_create_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranswer',
            name='create_datetime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
