# Generated by Django 5.1.1 on 2025-08-13 18:05

import app_test.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_test', '0003_alter_useranswer_create_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='image',
            field=models.ImageField(blank=True, upload_to=app_test.models.test_directoyr_path),
        ),
    ]
